# ========================
# DB2 数据源
# ========================

dbcompare.sources[0].source-name=DB2_A
dbcompare.sources[0].type=DB2
dbcompare.sources[0].jdbc-url=jdbc:db2://192.168.1.182:32001/LEGACYA
dbcompare.sources[0].username=db2inst1
dbcompare.sources[0].password=db2inst1pass
dbcompare.sources[0].schema=DB2INST1

dbcompare.sources[1].source-name=DB2_B
dbcompare.sources[1].type=DB2
dbcompare.sources[1].jdbc-url=jdbc:db2://192.168.1.183:32002/LEGACYB
dbcompare.sources[1].username=db2inst1
dbcompare.sources[1].password=db2inst1pass
dbcompare.sources[1].schema=DB2INST1


# ========================
# openGauss
# ========================

dbcompare.target.source-name=GAUSS
dbcompare.target.type=GAUSS
dbcompare.target.jdbc-url=jdbc:postgresql://192.168.1.183:32432/postgres
dbcompare.target.username=testuser
dbcompare.target.password=Test@123


# ========================
# 映射关系（关键??）
# ========================

dbcompare.mappings[0].source-database-name=DB2_A
dbcompare.mappings[0].target-schema-name=og_db2_1

dbcompare.mappings[1].source-database-name=DB2_B
dbcompare.mappings[1].target-schema-name=og_db2_2


# ========================
# 对比选项
# ========================

dbcompare.options.compare-nullable=true
dbcompare.options.compare-default-value=true
dbcompare.options.compare-length=true
dbcompare.options.source-load-threads=2


# ========================
# 输出
# ========================

dbcompare.output.csv-path=build/reports/default-compare-report.csv
dbcompare.output.excel-path=build/reports/default-compare-detail.xlsx
dbcompare.output.summary-path=build/reports/default-compare-summary.txt
