# Default type equality rules.
# Users can edit this file to decide which raw database types are treated as equal.
CHAR=CHAR,CHARACTER,GRAPHIC
VARCHAR=VARCHAR,CHARACTER VARYING,VARGRAPHIC
SMALLINT=SMALLINT
INT=INT,INTEGER,INT4,NUMBER
BIGINT=BIGINT
NUMERIC=NUMERIC,DECIMAL
DATE=DATE,TIMESTAMP
