-- DB2_A 测试脚本
-- 连接到 LEGACYA 数据库后执行
-- 例如：
--   db2 connect to LEGACYA user db2inst1 using db2inst1pass
--   db2 -td@ -vf examples/sql/db2_a_setup.sql
--
--#SET TERMINATOR @

BEGIN
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
    EXECUTE IMMEDIATE 'DROP TABLE DB2INST1.PRODUCT';
    EXECUTE IMMEDIATE 'DROP TABLE DB2INST1.ORDER_HEADER';
    EXECUTE IMMEDIATE 'DROP TABLE DB2INST1.CUSTOMER';
END
@

SET CURRENT SCHEMA DB2INST1
@

CREATE TABLE DB2INST1.CUSTOMER (
    CUSTOMER_ID   INTEGER       NOT NULL,
    CUSTOMER_NAME VARCHAR(80)   NOT NULL,
    CUSTOMER_TYPE CHAR(1)       NOT NULL DEFAULT 'N',
    PHONE         VARCHAR(20),
    CREATED_AT    TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (CUSTOMER_ID)
)
@

CREATE TABLE DB2INST1.ORDER_HEADER (
    ORDER_ID      INTEGER        NOT NULL,
    CUSTOMER_ID   INTEGER        NOT NULL,
    ORDER_NO      VARCHAR(32)    NOT NULL,
    STATUS        VARCHAR(20)    NOT NULL DEFAULT 'NEW',
    ORDER_AMOUNT  DECIMAL(12,2)  NOT NULL DEFAULT 0,
    REMARK        VARCHAR(100),
    CREATED_AT    TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (ORDER_ID)
)
@

CREATE TABLE DB2INST1.PRODUCT (
    PRODUCT_ID    INTEGER        NOT NULL,
    PRODUCT_CODE  VARCHAR(30)    NOT NULL,
    PRODUCT_NAME  VARCHAR(100)   NOT NULL,
    UNIT_PRICE    DECIMAL(10,2)  NOT NULL DEFAULT 0,
    ENABLED_FLAG  CHAR(1)        NOT NULL DEFAULT 'Y',
    PRIMARY KEY (PRODUCT_ID)
)
@

INSERT INTO DB2INST1.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, PHONE)
VALUES
    (1, 'Alice', 'A', '13800000001'),
    (2, 'Bob',   'B', '13800000002')
@

INSERT INTO DB2INST1.ORDER_HEADER (ORDER_ID, CUSTOMER_ID, ORDER_NO, STATUS, ORDER_AMOUNT, REMARK)
VALUES
    (1001, 1, 'A-ORD-1001', 'NEW', 128.50, 'first order'),
    (1002, 2, 'A-ORD-1002', 'DONE', 256.00, 'second order')
@

INSERT INTO DB2INST1.PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE, ENABLED_FLAG)
VALUES
    (501, 'P-A-001', 'Keyboard', 199.00, 'Y'),
    (502, 'P-A-002', 'Mouse',     59.00, 'Y')
@
