-- DB2_B 测试脚本
-- 连接到 LEGACYB 数据库后执行
-- 例如：
--   db2 connect to LEGACYB user db2inst1 using db2inst1pass
--   db2 -td@ -vf examples/sql/db2_b_setup.sql
--
--#SET TERMINATOR @

BEGIN
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
    EXECUTE IMMEDIATE 'DROP TABLE DB2INST1.REGION';
    EXECUTE IMMEDIATE 'DROP TABLE DB2INST1.TXN_LOG';
    EXECUTE IMMEDIATE 'DROP TABLE DB2INST1.ACCOUNT';
END
@

SET CURRENT SCHEMA DB2INST1
@

CREATE TABLE DB2INST1.ACCOUNT (
    ACCOUNT_ID     INTEGER        NOT NULL,
    ACCOUNT_NO     VARCHAR(24)    NOT NULL,
    ACCOUNT_NAME   VARCHAR(80)    NOT NULL,
    ACCOUNT_STATUS CHAR(1)        NOT NULL DEFAULT 'A',
    OPEN_DATE      DATE           NOT NULL,
    PRIMARY KEY (ACCOUNT_ID)
)
@

CREATE TABLE DB2INST1.TXN_LOG (
    TXN_ID         INTEGER         NOT NULL,
    ACCOUNT_ID     INTEGER         NOT NULL,
    TXN_NO         VARCHAR(30)     NOT NULL,
    TXN_AMOUNT     DECIMAL(14,2)   NOT NULL DEFAULT 0,
    TXN_STATUS     VARCHAR(20)     NOT NULL DEFAULT 'INIT',
    CREATED_AT     TIMESTAMP       NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (TXN_ID)
)
@

CREATE TABLE DB2INST1.REGION (
    REGION_CODE    VARCHAR(10)    NOT NULL,
    REGION_NAME    VARCHAR(50)    NOT NULL,
    ENABLED_FLAG   CHAR(1)        NOT NULL DEFAULT 'Y',
    PRIMARY KEY (REGION_CODE)
)
@

INSERT INTO DB2INST1.ACCOUNT (ACCOUNT_ID, ACCOUNT_NO, ACCOUNT_NAME, ACCOUNT_STATUS, OPEN_DATE)
VALUES
    (2001, 'ACC-B-0001', 'Main Account', 'A', DATE('2024-01-01')),
    (2002, 'ACC-B-0002', 'Reserve Account', 'A', DATE('2024-02-01'))
@

INSERT INTO DB2INST1.TXN_LOG (TXN_ID, ACCOUNT_ID, TXN_NO, TXN_AMOUNT, TXN_STATUS)
VALUES
    (3001, 2001, 'TXN-B-0001', 1000.25, 'INIT'),
    (3002, 2002, 'TXN-B-0002', 2500.00, 'DONE')
@

INSERT INTO DB2INST1.REGION (REGION_CODE, REGION_NAME, ENABLED_FLAG)
VALUES
    ('NORTH', 'North Region', 'Y'),
    ('SOUTH', 'South Region', 'Y')
@
